//HintName: Cloneable.Snapshots.Playground.DeepClone.cloneable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;

namespace Cloneable.Snapshots.Playground;
public partial class DeepClone
{
    /// <summary>
    /// Creates a copy of DeepClone with NO circular reference checking. This method should be used if performance matters.
    /// <exception cref="StackOverflowException">Will occur on any object that has circular references in the hierarchy.</exception>
    /// </summary>
    public global::Cloneable.Snapshots.Playground.DeepClone Clone()
    {
        return new global::Cloneable.Snapshots.Playground.DeepClone
        {
            A = this.A,
            Simple = this.Simple.Clone(),
        };
    }
    /// <summary>
    /// Creates a copy of DeepClone with circular reference checking. If a circular reference was detected, only a reference of the leaf object is passed instead of cloning it.
    /// </summary>
    /// <param name="referenceChain">Should only be provided if specific objects should not be cloned but passed by reference instead.</param>
    public global::Cloneable.Snapshots.Playground.DeepClone CloneSafe(global::System.Collections.Generic.Stack<object>? referenceChain = null)
    {
        if (referenceChain?.Contains(this) == true) return this;
        referenceChain ??= new global::System.Collections.Generic.Stack<object>();
        referenceChain.Push(this);
        var clone = new global::Cloneable.Snapshots.Playground.DeepClone
        {
            A = this.A,
            Simple = this.Simple.CloneSafe(referenceChain),
        };
        referenceChain.Pop();
        return clone;
    }
}
