//HintName: Cloneable.Sample.SimpleClone.cloneable.g.cs
// <auto-generated/>
using System;
using System.Linq;

namespace Cloneable.Sample;
public partial class SimpleClone
{
    /// <summary>

    /// Creates a copy of SimpleClone with NO circular reference checking. This method should be used if performance matters.

    /// 

    /// <exception cref="StackOverflowException">Will occur on any object that has circular references in the hierarchy.</exception>

    /// </summary>
    public global::Cloneable.Sample.SimpleClone Clone()
    {
        return new global::Cloneable.Sample.SimpleClone
        {
            A = this.A,
        };
    }
    /// <summary>

    /// Creates a copy of SimpleClone with circular reference checking. If a circular reference was detected, only a reference of the leaf object is passed instead of cloning it.

    /// </summary>

    /// <param name="referenceChain">Should only be provided if specific objects should not be cloned but passed by reference instead.</param>
    public global::Cloneable.Sample.SimpleClone CloneSafe(global::System.Collections.Generic.Stack<object> referenceChain = null)
    {
        if (referenceChain?.Contains(this) == true) return this;
        referenceChain ??= new global::System.Collections.Generic.Stack<object>();
        referenceChain.Push(this);
        var clone = new global::Cloneable.Sample.SimpleClone
        {
            A = this.A,
        };
        referenceChain.Pop();
        return clone;
    }
}
